### ISSUE TITLE
how can i get the rjr-s3-native

### ISSUE THREAD

**Issue by ai-dlc** [annesadleir/rjr-s3-native#4]
```
Then use GraalVM's native-image command to create the native executable:
native-image --enable-url-protocols=http,https -cp ./target/rjr-s3-native-1.0.jar -Djava.net.preferIPv4Stack=true -H:Name=rjr-s3-native -H:Class=uk.co.littlestickyleaves.lambda.S3LambdaMain -H:+ReportUnsupportedElementsAtRuntime --allow-incomplete-classpath -H:+TraceClassInitialization --no-fallback --initialize-at-build-time

NB The config in the META-INF/native-image folder of this repo was created using the [Tracing Agent](https://medium.com/graalvm/introducing-the-tracing-agent-simplifying-graalvm-native-image-configuration-c3b56c486271) against the TracingAgentPath class.
```
this command is not use for me
but i got error :Non-boolean option 'TraceClassInitialization' can not use +/- prefix. Use 'TraceClassInitialization=<value>' format

so how can  i  get the  rjr-s3-native file

**Comment by annesadleir** [comment]
Hi, I haven't updated this in a while, and I think the GraalVM native command flags have changed a bit.  I'd suggest either omitting that one and seeing what happens, or else using the Graal native Maven plugin instead.  I've got an example of its use here: https://github.com/annesadleir/rjr-aws-lambda-dummy/blob/master/pom.xml
but it's also got useful docs.  Good luck! I hope it works for you

**Comment by ai-dlc** [comment]
Thanks you a lot, i am trying
